Dj_Insta_accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import register

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name = 'login'),
    path('logout/', auth_view.LogoutView.as_view(template_name = 'registration/logout.html'), name = 'logout'),
    path('register/', register, name = 'register'),
]

Dj_Insta_photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView

from .views import *
from .models import Photo

# namespace로 사용되는 값. 템플릿에서 URL 템플릿 태그를 사용할 때 [app_name:URL패턴이름] 형태로 사용 
app_name = 'photo'

urlpatterns = [
    path('', photo_list, name = 'photo_list'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name = 'photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name = 'photo_update'),
    # DetailView는 urls.py에서 인라인 코드로 작성할 수 있다.
    path('detail/<int:pk>/', DetailView.as_view(model = Photo, template_name = 'Dj_Insta_photo/detail.html'), name='photo_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls.static import static
# from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Dj_Insta_photo.urls')),
    path('accounts/', include('Dj_Insta_accounts.urls'))
]

# static을 사용하여 MEDIA_URL에 해당하는 주소를 가진 요청에 대해서 MEDIA_ROOT에서 찾아서 응답하도록 설정
# urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Dj_Insta_accounts/models.py
from django.db import models

# Create your models here.

Dj_Insta_photo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Photo(models.Model):
    # ForeignKey를 사용하여  User 태아블과 관계를 생성
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_photos')
    
    photo = models.ImageField(upload_to = 'photos/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField()

    # 글 작성 일을 객체가 추가될 때 자동으로 설정
    created = models.DateTimeField(auto_now_add=True)
    # 글 수정 일을 수정될 때 자동으로 설정
    updated = models.DateTimeField(auto_now=True)

    # 해당 모델의 객체들의 정렬 기준을 설정 [ updated --> 내림차순 ]
    class Meta:
        ordering = ['-updated']

    # 해당 클레스 요청 시 반환값 설정  [ 작성자 이름과 글 작성일 반환 ]
    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")
    
    # 객체의 상세 페이지의 주소를 반환
    def get_absolute_url(self):
        # reverse : URL 패턴이름을 가지고 해당 패턴을 찾아 주소로 만들어주는 함수
        return reverse('photo:photo_detail', args=[str(self.id)])

Dj_Insta_accounts/forms.py
from django.contrib.auth.models import User
from django import forms

# 회원 가입을 위한 FORM
class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    # 각 필드의 clean 메소드가 호출된 후에 호출되는 메소드. 유효성 검사나 조작을 하고싶을 때 사용
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords not matched!')
        return cd['password2']

Dj_Insta_accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm

# 회원 가입 FORM을 위한 VIEW
def register(request):
    # 회원 가입 정보가 서버로 전달 됐을 경우
    if request.method == 'POST':
        user_form = RegisterForm(request.POST)
        # user_form이 유효하다면.
        if user_form.is_valid():
            # 폼 객체에 지정된 모델을 확인하고, 객체 생성 | commit=False --> 메모리 상에 객체만 생성
            new_user = user_form.save(commit=False)
            # set_password : 비밀번호를 지정
            new_user.set_password(user_form.cleaned_data['password'])
            # 실제로 DB에 비밀번호를 저장
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user':new_user})
    else:
        user_form = RegisterForm()
    
    return render(request, 'registration/register.html', {'form':user_form})

Dj_Insta_photo/views.py
from django.shortcuts import render
from django.views import generic
from .models import Photo
from django.shortcuts import redirect
# 함수형 뷰에서 사용하는 권한 제한
from django.contrib.auth.decorators import login_required
# 클레스형 뷰애서 사용하는 권한 제한
from django.contrib.auth.mixins import LoginRequiredMixin


@login_required
def photo_list(request):
    photos = Photo.objects.all()
    return render(request, 'Dj_Insta_photo/list.html', {'photos':photos})

class PhotoUploadView(LoginRequiredMixin, generic.CreateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'Dj_Insta_photo/upload.html'

    # 업로드 후 이동할 페이지를 호출
    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form':form})

class PhotoDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Photo
    success_url = '/'
    template_name = 'Dj_Insta_photo/delete.html'

class PhotoUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'Dj_Insta_photo/update.html'

Dj_Insta_photo/templates/Dj_Insta_photo/delete.html
{% extends 'base.html' %}

{% block title %}- Delete{% endblock%}

{% block content %}
    <div class = "row">
        <div class = "col-md-2"></div>
        <div class = "col-md-8 panel panel-default">
            <div class = "alter alter-info">
                <h4><strong>Do you want to delete {{object}}?</strong></h4>
            </div>
            <form action="" method="post">
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Confirm">
            </form>
        </div>
        <div class = "col-md-2"></div>
    </div>
{% endblock %}

Dj_Insta_photo/templates/Dj_Insta_photo/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.text|truncatechars:10 }}
{% endblock%}

{% block content %}
<div class = "row">
    <div class = "col-md-2"></div>
    <div class = "col-md-8 panel panel-default">
        <p><img src="{{object.photo.url}}" style="width:500px;"></p>
        <button type="button" class="btn btn-outline-primary btn-sm">{{object.author.username}}</button>
        <p>{{object.text|linebreaksbr}}</p>
        <p class = "text-right"> 
            <a href = "{% url 'photo:photo_update' pk=object.id %}" class = "btn btn-outline-danger btn-sm float-right">Update</a>
            <a href = "{% url 'photo:photo_delete' pk=object.id %}" class = "btn btn-outline-danger btn-sm float-right">Delete</a>
        </p>
        {% load disqus_tags %}
        {% disqus_show_comments %}
    </div>
    <div class = "col-md-2"></div>
</div>
{% endblock %}

Dj_Insta_photo/templates/Dj_Insta_photo/list.html
{% extends 'base.html' %}

{% block title %}- List{% endblock%}

{% block content %}
    {% for post in photos %}
    <div class = "row">
        <div class = "col-md-2"></div>
        <div class = "col-md-8 panel panel-default">
            <p><img src = "{{post.photo.url}}" style="width: 500px;"></p>
            <button type = "button" class = "btn btn-xs btn-info"> {{post.author.username}} </button>
            <p> {{post.text | linebreaksbr }}</p>
            <p class = "text-right">
                <a href="{% url 'photo:photo_detail' pk=post.id %}" class = "btn btn-xs btn-success">댓글달기</a>
            </p>
        </div>
        <div class = "col-md-2"></div>
    </div>
    {% endfor %}
{% endblock %}

Dj_Insta_photo/templates/Dj_Insta_photo/update.html
{% extends 'base.html' %}

{% block title %}- Update{% endblock%}

{% block content %}
    <div class = "row">
        <div class = "col-md-2"></div>
        <div class = "col-md-8 panel panel-default">
            <form action="" method="post" enctype="multipart/form-data">
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" class = "btn btn-primary" value="Update">
            </form>
        </div>
        <div class = "col-md-2"></div>
    </div>
{% endblock %}

Dj_Insta_photo/templates/Dj_Insta_photo/upload.html
{% extends 'base.html' %}

{% block title %}- Upload{% endblock%}

{% block content %}
<div class = "row">
    <div class = "col-md-2"></div>
    <div class = "col-md-8 panel panel-default">
        <!-- enctype : form태그로 작성한 정보를 어떤 형태로 전달할 것인지 결정하는 옵션 -->
        <form action="" method="post" enctype="multipart/form-data">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class = "btn btn-primary" value="Upload">
        </form>
    </div>
    <div class = "col-md-2"></div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrinkto-fit=no">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <title>Dstagram {% block title %}{% endblock %}</title>
</head>
<body>

<div class = "container">
    <header class = "header clearfix">
        <nav class = "navbar navbar-expand-lg navbar-light bg-light">
            <a class = "navbar-brand" href="/">Dstagram</a> 
            <ul class = "nav">
                <li class = "nav-item"><a href="/" class = "active nav-link">Home</a></li>

                {% if user.is_authenticated %}
                <li class = "nav-item"><a href="#" class = "nav-link">Welcome, {{user.get_username}}</a></li>
                <li class = "nav-item"><a href="{% url 'photo:photo_upload' %}" class = "nav-link">Upload</a></li>
                <li class = "nav-item"><a href="{% url 'logout' %}" class = "nav-link">Logout</a></li>
                {% else %}
                <li class = "nav-item"><a href="{% url 'login' %}" class = "nav-link">Login</a></li>
                <li class = "nav-item"><a href="{% url 'register' %}" class = "nav-link">Sign Up</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    {% block content %}
    {% endblock %}

    <footer class = "footer">
        <p>&copy; 2022 KUK_S.J  Powerd By Django</p>
    </footer>
</div>
    
</body>
</html>